server:
  port: 8888
  servlet:
    context-path: /SevanUp
spring:
  datasource:
    url: jdbc:mysql://124.222.167.129:3310/test_db?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# mybatis-plus-boot-starter 写法
mybatis-plus:
#  #todo * ** 有什么区别
  mapperLocations: classpath:mybatis/**/*Mapper.xml
  typeAliasesPackage: com.vvvv.sevanUp.model.*

#  mybatis-spring-boot-starter 写法
#mybatis:
#  mapper-locations: classpath:mybatis/excel/SubsinstSynTempMapper.xml
#  type-aliases-package: com.vvvv.sevanUp.model.excel.*

logging:
  level:
    com.vvvv.mapper: debug

#xss攻击拦截
xss:
  enabled: true
  excludes:
  urlPatterns: /*

kafka:
  bootstrap-servers: 47.96.238.1:9092
  producer:
    retries: 1
    batch-size: 10000  #每次发送大小
    buffer-memory: 33554432
    key-serializer: org.apache.kafka.common.serialization.StringSerializer #编码格式
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    group-id: vvvv
    auto-offset-reset: earliest #当Kafka中没有初始偏移量或者服务器上不再存在当前偏移量时该怎么办，默认值为latest，表示自动将偏移重置为最新的偏移量
    enable-auto-commit: true  #如果为true，则消费者的偏移量将在后台定期提交，默认值为tru
    auto-commit-interval: 100  #如果'enable.auto.commit'为true，则消费者偏移自动提交给Kafka的频率（以毫秒为单位），默认值为5000。
    key-serializer: org.apache.kafka.common.serialization.StringSerializer #编码格式
    value-serializer: org.apache.kafka.common.serialization.StringSerializer