server:
  port: 8887
  servlet:
    context-path: /SevanUp
spring:
  datasource:
    url: jdbc:mysql://ip:port/test_db?characterEncoding=utf-8&useSSL=false
    username: username
    password: ps
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: ip
    port: port
    password: ps
    database: 0
    # 连接超时时间（毫秒）
    timeout: 1800000
    lettuce:
      pool:
        # 连接池的最大连接数（使用负值表示没有限制）
        max-active: 20
        # 最大阻塞等待时间（负值表示没有限制）
        max-wait: -1
        # 连接池的最大空闲连接
        max-idle: 5
        # 连接池的最小空闲连接
        min-idle: 0


# mybatis-plus-boot-starter 写法
mybatis-plus:
#  #todo * ** 有什么区别
  mapperLocations: classpath:mybatis/**/*Mapper.xml
  typeAliasesPackage: com.vvvv.sevanUp.model.*

#  mybatis-spring-boot-starter 写法
#mybatis:
#  mapper-locations: classpath:mybatis/excel/SubsinstSynTempMapper.xml
#  type-aliases-package: com.vvvv.sevanUp.model.excel.*

logging:
  level:
    com.vvvv.mapper: info

#xss攻击拦截
xss:
  enabled: true
  excludes:
  urlPatterns: /*

kafka:
  bootstrap-servers: 47.96.238.1:9092
  producer:
    retries: 1
    batch-size: 10000  #每次发送大小
    buffer-memory: 33554432
    key-serializer: org.apache.kafka.common.serialization.StringSerializer #编码格式
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    group-id: vvvv
    auto-offset-reset: earliest #当Kafka中没有初始偏移量或者服务器上不再存在当前偏移量时该怎么办，默认值为latest，表示自动将偏移重置为最新的偏移量
    enable-auto-commit: true  #如果为true，则消费者的偏移量将在后台定期提交，默认值为tru
    auto-commit-interval: 100  #如果'enable.auto.commit'为true，则消费者偏移自动提交给Kafka的频率（以毫秒为单位），默认值为5000。
    key-serializer: org.apache.kafka.common.serialization.StringSerializer #编码格式
    value-serializer: org.apache.kafka.common.serialization.StringSerializer

## 轻量级HTTP客户端框架forest
forest:
  # 配置底层API为 okhttp3
  backend: okhttp3
  # 连接池最大连接数，默认值为500
  max-connections: 1000
  # 每个路由的最大连接数，默认值为500
  max-route-connections: 500
  # 请求超时时间，单位为毫秒, 默认值为3000
  timeout: 3000
  # 连接超时时间，单位为毫秒, 默认值为2000
  connect-timeout: 3000
  # 请求失败后重试次数，默认为0次不重试
  retry-count: 1
  # 单向验证的HTTPS的默认SSL协议，默认为SSLv3
  ssl-protocol: SSLv3
  # 打开或关闭日志，默认为true
  logEnabled: true
  # 打开/关闭Forest请求日志（默认为 true）
  log-request: true
  # 打开/关闭Forest响应状态日志（默认为 true）
  log-response-status: true
  # 打开/关闭Forest响应内容日志（默认为 false）
  log-response-content: true
