package com.vvvv.sevanUp.model.excel;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SubsinstSynTempExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUBSINST_SYN_TEMP
     *
     * @mbg.generated Thu May 26 09:46:38 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUBSINST_SYN_TEMP
     *
     * @mbg.generated Thu May 26 09:46:38 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUBSINST_SYN_TEMP
     *
     * @mbg.generated Thu May 26 09:46:38 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSINST_SYN_TEMP
     *
     * @mbg.generated Thu May 26 09:46:38 CST 2022
     */
    public SubsinstSynTempExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSINST_SYN_TEMP
     *
     * @mbg.generated Thu May 26 09:46:38 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSINST_SYN_TEMP
     *
     * @mbg.generated Thu May 26 09:46:38 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSINST_SYN_TEMP
     *
     * @mbg.generated Thu May 26 09:46:38 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSINST_SYN_TEMP
     *
     * @mbg.generated Thu May 26 09:46:38 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSINST_SYN_TEMP
     *
     * @mbg.generated Thu May 26 09:46:38 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSINST_SYN_TEMP
     *
     * @mbg.generated Thu May 26 09:46:38 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSINST_SYN_TEMP
     *
     * @mbg.generated Thu May 26 09:46:38 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSINST_SYN_TEMP
     *
     * @mbg.generated Thu May 26 09:46:38 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSINST_SYN_TEMP
     *
     * @mbg.generated Thu May 26 09:46:38 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSINST_SYN_TEMP
     *
     * @mbg.generated Thu May 26 09:46:38 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SUBSINST_SYN_TEMP
     *
     * @mbg.generated Thu May 26 09:46:38 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSystemidIsNull() {
            addCriterion("SYSTEMID is null");
            return (Criteria) this;
        }

        public Criteria andSystemidIsNotNull() {
            addCriterion("SYSTEMID is not null");
            return (Criteria) this;
        }

        public Criteria andSystemidEqualTo(String value) {
            addCriterion("SYSTEMID =", value, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidNotEqualTo(String value) {
            addCriterion("SYSTEMID <>", value, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidGreaterThan(String value) {
            addCriterion("SYSTEMID >", value, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidGreaterThanOrEqualTo(String value) {
            addCriterion("SYSTEMID >=", value, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidLessThan(String value) {
            addCriterion("SYSTEMID <", value, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidLessThanOrEqualTo(String value) {
            addCriterion("SYSTEMID <=", value, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidLike(String value) {
            addCriterion("SYSTEMID like", value, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidNotLike(String value) {
            addCriterion("SYSTEMID not like", value, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidIn(List<String> values) {
            addCriterion("SYSTEMID in", values, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidNotIn(List<String> values) {
            addCriterion("SYSTEMID not in", values, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidBetween(String value1, String value2) {
            addCriterion("SYSTEMID between", value1, value2, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidNotBetween(String value1, String value2) {
            addCriterion("SYSTEMID not between", value1, value2, "systemid");
            return (Criteria) this;
        }

        public Criteria andReginidIsNull() {
            addCriterion("REGINID is null");
            return (Criteria) this;
        }

        public Criteria andReginidIsNotNull() {
            addCriterion("REGINID is not null");
            return (Criteria) this;
        }

        public Criteria andReginidEqualTo(String value) {
            addCriterion("REGINID =", value, "reginid");
            return (Criteria) this;
        }

        public Criteria andReginidNotEqualTo(String value) {
            addCriterion("REGINID <>", value, "reginid");
            return (Criteria) this;
        }

        public Criteria andReginidGreaterThan(String value) {
            addCriterion("REGINID >", value, "reginid");
            return (Criteria) this;
        }

        public Criteria andReginidGreaterThanOrEqualTo(String value) {
            addCriterion("REGINID >=", value, "reginid");
            return (Criteria) this;
        }

        public Criteria andReginidLessThan(String value) {
            addCriterion("REGINID <", value, "reginid");
            return (Criteria) this;
        }

        public Criteria andReginidLessThanOrEqualTo(String value) {
            addCriterion("REGINID <=", value, "reginid");
            return (Criteria) this;
        }

        public Criteria andReginidLike(String value) {
            addCriterion("REGINID like", value, "reginid");
            return (Criteria) this;
        }

        public Criteria andReginidNotLike(String value) {
            addCriterion("REGINID not like", value, "reginid");
            return (Criteria) this;
        }

        public Criteria andReginidIn(List<String> values) {
            addCriterion("REGINID in", values, "reginid");
            return (Criteria) this;
        }

        public Criteria andReginidNotIn(List<String> values) {
            addCriterion("REGINID not in", values, "reginid");
            return (Criteria) this;
        }

        public Criteria andReginidBetween(String value1, String value2) {
            addCriterion("REGINID between", value1, value2, "reginid");
            return (Criteria) this;
        }

        public Criteria andReginidNotBetween(String value1, String value2) {
            addCriterion("REGINID not between", value1, value2, "reginid");
            return (Criteria) this;
        }

        public Criteria andProdspeccodeIsNull() {
            addCriterion("PRODSPECCODE is null");
            return (Criteria) this;
        }

        public Criteria andProdspeccodeIsNotNull() {
            addCriterion("PRODSPECCODE is not null");
            return (Criteria) this;
        }

        public Criteria andProdspeccodeEqualTo(String value) {
            addCriterion("PRODSPECCODE =", value, "prodspeccode");
            return (Criteria) this;
        }

        public Criteria andProdspeccodeNotEqualTo(String value) {
            addCriterion("PRODSPECCODE <>", value, "prodspeccode");
            return (Criteria) this;
        }

        public Criteria andProdspeccodeGreaterThan(String value) {
            addCriterion("PRODSPECCODE >", value, "prodspeccode");
            return (Criteria) this;
        }

        public Criteria andProdspeccodeGreaterThanOrEqualTo(String value) {
            addCriterion("PRODSPECCODE >=", value, "prodspeccode");
            return (Criteria) this;
        }

        public Criteria andProdspeccodeLessThan(String value) {
            addCriterion("PRODSPECCODE <", value, "prodspeccode");
            return (Criteria) this;
        }

        public Criteria andProdspeccodeLessThanOrEqualTo(String value) {
            addCriterion("PRODSPECCODE <=", value, "prodspeccode");
            return (Criteria) this;
        }

        public Criteria andProdspeccodeLike(String value) {
            addCriterion("PRODSPECCODE like", value, "prodspeccode");
            return (Criteria) this;
        }

        public Criteria andProdspeccodeNotLike(String value) {
            addCriterion("PRODSPECCODE not like", value, "prodspeccode");
            return (Criteria) this;
        }

        public Criteria andProdspeccodeIn(List<String> values) {
            addCriterion("PRODSPECCODE in", values, "prodspeccode");
            return (Criteria) this;
        }

        public Criteria andProdspeccodeNotIn(List<String> values) {
            addCriterion("PRODSPECCODE not in", values, "prodspeccode");
            return (Criteria) this;
        }

        public Criteria andProdspeccodeBetween(String value1, String value2) {
            addCriterion("PRODSPECCODE between", value1, value2, "prodspeccode");
            return (Criteria) this;
        }

        public Criteria andProdspeccodeNotBetween(String value1, String value2) {
            addCriterion("PRODSPECCODE not between", value1, value2, "prodspeccode");
            return (Criteria) this;
        }

        public Criteria andUseridtypeIsNull() {
            addCriterion("USERIDTYPE is null");
            return (Criteria) this;
        }

        public Criteria andUseridtypeIsNotNull() {
            addCriterion("USERIDTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andUseridtypeEqualTo(String value) {
            addCriterion("USERIDTYPE =", value, "useridtype");
            return (Criteria) this;
        }

        public Criteria andUseridtypeNotEqualTo(String value) {
            addCriterion("USERIDTYPE <>", value, "useridtype");
            return (Criteria) this;
        }

        public Criteria andUseridtypeGreaterThan(String value) {
            addCriterion("USERIDTYPE >", value, "useridtype");
            return (Criteria) this;
        }

        public Criteria andUseridtypeGreaterThanOrEqualTo(String value) {
            addCriterion("USERIDTYPE >=", value, "useridtype");
            return (Criteria) this;
        }

        public Criteria andUseridtypeLessThan(String value) {
            addCriterion("USERIDTYPE <", value, "useridtype");
            return (Criteria) this;
        }

        public Criteria andUseridtypeLessThanOrEqualTo(String value) {
            addCriterion("USERIDTYPE <=", value, "useridtype");
            return (Criteria) this;
        }

        public Criteria andUseridtypeLike(String value) {
            addCriterion("USERIDTYPE like", value, "useridtype");
            return (Criteria) this;
        }

        public Criteria andUseridtypeNotLike(String value) {
            addCriterion("USERIDTYPE not like", value, "useridtype");
            return (Criteria) this;
        }

        public Criteria andUseridtypeIn(List<String> values) {
            addCriterion("USERIDTYPE in", values, "useridtype");
            return (Criteria) this;
        }

        public Criteria andUseridtypeNotIn(List<String> values) {
            addCriterion("USERIDTYPE not in", values, "useridtype");
            return (Criteria) this;
        }

        public Criteria andUseridtypeBetween(String value1, String value2) {
            addCriterion("USERIDTYPE between", value1, value2, "useridtype");
            return (Criteria) this;
        }

        public Criteria andUseridtypeNotBetween(String value1, String value2) {
            addCriterion("USERIDTYPE not between", value1, value2, "useridtype");
            return (Criteria) this;
        }

        public Criteria andProductnoIsNull() {
            addCriterion("PRODUCTNO is null");
            return (Criteria) this;
        }

        public Criteria andProductnoIsNotNull() {
            addCriterion("PRODUCTNO is not null");
            return (Criteria) this;
        }

        public Criteria andProductnoEqualTo(String value) {
            addCriterion("PRODUCTNO =", value, "productno");
            return (Criteria) this;
        }

        public Criteria andProductnoNotEqualTo(String value) {
            addCriterion("PRODUCTNO <>", value, "productno");
            return (Criteria) this;
        }

        public Criteria andProductnoGreaterThan(String value) {
            addCriterion("PRODUCTNO >", value, "productno");
            return (Criteria) this;
        }

        public Criteria andProductnoGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCTNO >=", value, "productno");
            return (Criteria) this;
        }

        public Criteria andProductnoLessThan(String value) {
            addCriterion("PRODUCTNO <", value, "productno");
            return (Criteria) this;
        }

        public Criteria andProductnoLessThanOrEqualTo(String value) {
            addCriterion("PRODUCTNO <=", value, "productno");
            return (Criteria) this;
        }

        public Criteria andProductnoLike(String value) {
            addCriterion("PRODUCTNO like", value, "productno");
            return (Criteria) this;
        }

        public Criteria andProductnoNotLike(String value) {
            addCriterion("PRODUCTNO not like", value, "productno");
            return (Criteria) this;
        }

        public Criteria andProductnoIn(List<String> values) {
            addCriterion("PRODUCTNO in", values, "productno");
            return (Criteria) this;
        }

        public Criteria andProductnoNotIn(List<String> values) {
            addCriterion("PRODUCTNO not in", values, "productno");
            return (Criteria) this;
        }

        public Criteria andProductnoBetween(String value1, String value2) {
            addCriterion("PRODUCTNO between", value1, value2, "productno");
            return (Criteria) this;
        }

        public Criteria andProductnoNotBetween(String value1, String value2) {
            addCriterion("PRODUCTNO not between", value1, value2, "productno");
            return (Criteria) this;
        }

        public Criteria andVproductidIsNull() {
            addCriterion("VPRODUCTID is null");
            return (Criteria) this;
        }

        public Criteria andVproductidIsNotNull() {
            addCriterion("VPRODUCTID is not null");
            return (Criteria) this;
        }

        public Criteria andVproductidEqualTo(String value) {
            addCriterion("VPRODUCTID =", value, "vproductid");
            return (Criteria) this;
        }

        public Criteria andVproductidNotEqualTo(String value) {
            addCriterion("VPRODUCTID <>", value, "vproductid");
            return (Criteria) this;
        }

        public Criteria andVproductidGreaterThan(String value) {
            addCriterion("VPRODUCTID >", value, "vproductid");
            return (Criteria) this;
        }

        public Criteria andVproductidGreaterThanOrEqualTo(String value) {
            addCriterion("VPRODUCTID >=", value, "vproductid");
            return (Criteria) this;
        }

        public Criteria andVproductidLessThan(String value) {
            addCriterion("VPRODUCTID <", value, "vproductid");
            return (Criteria) this;
        }

        public Criteria andVproductidLessThanOrEqualTo(String value) {
            addCriterion("VPRODUCTID <=", value, "vproductid");
            return (Criteria) this;
        }

        public Criteria andVproductidLike(String value) {
            addCriterion("VPRODUCTID like", value, "vproductid");
            return (Criteria) this;
        }

        public Criteria andVproductidNotLike(String value) {
            addCriterion("VPRODUCTID not like", value, "vproductid");
            return (Criteria) this;
        }

        public Criteria andVproductidIn(List<String> values) {
            addCriterion("VPRODUCTID in", values, "vproductid");
            return (Criteria) this;
        }

        public Criteria andVproductidNotIn(List<String> values) {
            addCriterion("VPRODUCTID not in", values, "vproductid");
            return (Criteria) this;
        }

        public Criteria andVproductidBetween(String value1, String value2) {
            addCriterion("VPRODUCTID between", value1, value2, "vproductid");
            return (Criteria) this;
        }

        public Criteria andVproductidNotBetween(String value1, String value2) {
            addCriterion("VPRODUCTID not between", value1, value2, "vproductid");
            return (Criteria) this;
        }

        public Criteria andSpidIsNull() {
            addCriterion("SPID is null");
            return (Criteria) this;
        }

        public Criteria andSpidIsNotNull() {
            addCriterion("SPID is not null");
            return (Criteria) this;
        }

        public Criteria andSpidEqualTo(String value) {
            addCriterion("SPID =", value, "spid");
            return (Criteria) this;
        }

        public Criteria andSpidNotEqualTo(String value) {
            addCriterion("SPID <>", value, "spid");
            return (Criteria) this;
        }

        public Criteria andSpidGreaterThan(String value) {
            addCriterion("SPID >", value, "spid");
            return (Criteria) this;
        }

        public Criteria andSpidGreaterThanOrEqualTo(String value) {
            addCriterion("SPID >=", value, "spid");
            return (Criteria) this;
        }

        public Criteria andSpidLessThan(String value) {
            addCriterion("SPID <", value, "spid");
            return (Criteria) this;
        }

        public Criteria andSpidLessThanOrEqualTo(String value) {
            addCriterion("SPID <=", value, "spid");
            return (Criteria) this;
        }

        public Criteria andSpidLike(String value) {
            addCriterion("SPID like", value, "spid");
            return (Criteria) this;
        }

        public Criteria andSpidNotLike(String value) {
            addCriterion("SPID not like", value, "spid");
            return (Criteria) this;
        }

        public Criteria andSpidIn(List<String> values) {
            addCriterion("SPID in", values, "spid");
            return (Criteria) this;
        }

        public Criteria andSpidNotIn(List<String> values) {
            addCriterion("SPID not in", values, "spid");
            return (Criteria) this;
        }

        public Criteria andSpidBetween(String value1, String value2) {
            addCriterion("SPID between", value1, value2, "spid");
            return (Criteria) this;
        }

        public Criteria andSpidNotBetween(String value1, String value2) {
            addCriterion("SPID not between", value1, value2, "spid");
            return (Criteria) this;
        }

        public Criteria andProductoffertypeIsNull() {
            addCriterion("PRODUCTOFFERTYPE is null");
            return (Criteria) this;
        }

        public Criteria andProductoffertypeIsNotNull() {
            addCriterion("PRODUCTOFFERTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andProductoffertypeEqualTo(String value) {
            addCriterion("PRODUCTOFFERTYPE =", value, "productoffertype");
            return (Criteria) this;
        }

        public Criteria andProductoffertypeNotEqualTo(String value) {
            addCriterion("PRODUCTOFFERTYPE <>", value, "productoffertype");
            return (Criteria) this;
        }

        public Criteria andProductoffertypeGreaterThan(String value) {
            addCriterion("PRODUCTOFFERTYPE >", value, "productoffertype");
            return (Criteria) this;
        }

        public Criteria andProductoffertypeGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCTOFFERTYPE >=", value, "productoffertype");
            return (Criteria) this;
        }

        public Criteria andProductoffertypeLessThan(String value) {
            addCriterion("PRODUCTOFFERTYPE <", value, "productoffertype");
            return (Criteria) this;
        }

        public Criteria andProductoffertypeLessThanOrEqualTo(String value) {
            addCriterion("PRODUCTOFFERTYPE <=", value, "productoffertype");
            return (Criteria) this;
        }

        public Criteria andProductoffertypeLike(String value) {
            addCriterion("PRODUCTOFFERTYPE like", value, "productoffertype");
            return (Criteria) this;
        }

        public Criteria andProductoffertypeNotLike(String value) {
            addCriterion("PRODUCTOFFERTYPE not like", value, "productoffertype");
            return (Criteria) this;
        }

        public Criteria andProductoffertypeIn(List<String> values) {
            addCriterion("PRODUCTOFFERTYPE in", values, "productoffertype");
            return (Criteria) this;
        }

        public Criteria andProductoffertypeNotIn(List<String> values) {
            addCriterion("PRODUCTOFFERTYPE not in", values, "productoffertype");
            return (Criteria) this;
        }

        public Criteria andProductoffertypeBetween(String value1, String value2) {
            addCriterion("PRODUCTOFFERTYPE between", value1, value2, "productoffertype");
            return (Criteria) this;
        }

        public Criteria andProductoffertypeNotBetween(String value1, String value2) {
            addCriterion("PRODUCTOFFERTYPE not between", value1, value2, "productoffertype");
            return (Criteria) this;
        }

        public Criteria andProdofferidIsNull() {
            addCriterion("PRODOFFERID is null");
            return (Criteria) this;
        }

        public Criteria andProdofferidIsNotNull() {
            addCriterion("PRODOFFERID is not null");
            return (Criteria) this;
        }

        public Criteria andProdofferidEqualTo(String value) {
            addCriterion("PRODOFFERID =", value, "prodofferid");
            return (Criteria) this;
        }

        public Criteria andProdofferidNotEqualTo(String value) {
            addCriterion("PRODOFFERID <>", value, "prodofferid");
            return (Criteria) this;
        }

        public Criteria andProdofferidGreaterThan(String value) {
            addCriterion("PRODOFFERID >", value, "prodofferid");
            return (Criteria) this;
        }

        public Criteria andProdofferidGreaterThanOrEqualTo(String value) {
            addCriterion("PRODOFFERID >=", value, "prodofferid");
            return (Criteria) this;
        }

        public Criteria andProdofferidLessThan(String value) {
            addCriterion("PRODOFFERID <", value, "prodofferid");
            return (Criteria) this;
        }

        public Criteria andProdofferidLessThanOrEqualTo(String value) {
            addCriterion("PRODOFFERID <=", value, "prodofferid");
            return (Criteria) this;
        }

        public Criteria andProdofferidLike(String value) {
            addCriterion("PRODOFFERID like", value, "prodofferid");
            return (Criteria) this;
        }

        public Criteria andProdofferidNotLike(String value) {
            addCriterion("PRODOFFERID not like", value, "prodofferid");
            return (Criteria) this;
        }

        public Criteria andProdofferidIn(List<String> values) {
            addCriterion("PRODOFFERID in", values, "prodofferid");
            return (Criteria) this;
        }

        public Criteria andProdofferidNotIn(List<String> values) {
            addCriterion("PRODOFFERID not in", values, "prodofferid");
            return (Criteria) this;
        }

        public Criteria andProdofferidBetween(String value1, String value2) {
            addCriterion("PRODOFFERID between", value1, value2, "prodofferid");
            return (Criteria) this;
        }

        public Criteria andProdofferidNotBetween(String value1, String value2) {
            addCriterion("PRODOFFERID not between", value1, value2, "prodofferid");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSubscribetimeIsNull() {
            addCriterion("SUBSCRIBETIME is null");
            return (Criteria) this;
        }

        public Criteria andSubscribetimeIsNotNull() {
            addCriterion("SUBSCRIBETIME is not null");
            return (Criteria) this;
        }

        public Criteria andSubscribetimeEqualTo(String value) {
            addCriterion("SUBSCRIBETIME =", value, "subscribetime");
            return (Criteria) this;
        }

        public Criteria andSubscribetimeNotEqualTo(String value) {
            addCriterion("SUBSCRIBETIME <>", value, "subscribetime");
            return (Criteria) this;
        }

        public Criteria andSubscribetimeGreaterThan(String value) {
            addCriterion("SUBSCRIBETIME >", value, "subscribetime");
            return (Criteria) this;
        }

        public Criteria andSubscribetimeGreaterThanOrEqualTo(String value) {
            addCriterion("SUBSCRIBETIME >=", value, "subscribetime");
            return (Criteria) this;
        }

        public Criteria andSubscribetimeLessThan(String value) {
            addCriterion("SUBSCRIBETIME <", value, "subscribetime");
            return (Criteria) this;
        }

        public Criteria andSubscribetimeLessThanOrEqualTo(String value) {
            addCriterion("SUBSCRIBETIME <=", value, "subscribetime");
            return (Criteria) this;
        }

        public Criteria andSubscribetimeLike(String value) {
            addCriterion("SUBSCRIBETIME like", value, "subscribetime");
            return (Criteria) this;
        }

        public Criteria andSubscribetimeNotLike(String value) {
            addCriterion("SUBSCRIBETIME not like", value, "subscribetime");
            return (Criteria) this;
        }

        public Criteria andSubscribetimeIn(List<String> values) {
            addCriterion("SUBSCRIBETIME in", values, "subscribetime");
            return (Criteria) this;
        }

        public Criteria andSubscribetimeNotIn(List<String> values) {
            addCriterion("SUBSCRIBETIME not in", values, "subscribetime");
            return (Criteria) this;
        }

        public Criteria andSubscribetimeBetween(String value1, String value2) {
            addCriterion("SUBSCRIBETIME between", value1, value2, "subscribetime");
            return (Criteria) this;
        }

        public Criteria andSubscribetimeNotBetween(String value1, String value2) {
            addCriterion("SUBSCRIBETIME not between", value1, value2, "subscribetime");
            return (Criteria) this;
        }

        public Criteria andEffdateIsNull() {
            addCriterion("EFFDATE is null");
            return (Criteria) this;
        }

        public Criteria andEffdateIsNotNull() {
            addCriterion("EFFDATE is not null");
            return (Criteria) this;
        }

        public Criteria andEffdateEqualTo(String value) {
            addCriterion("EFFDATE =", value, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateNotEqualTo(String value) {
            addCriterion("EFFDATE <>", value, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateGreaterThan(String value) {
            addCriterion("EFFDATE >", value, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateGreaterThanOrEqualTo(String value) {
            addCriterion("EFFDATE >=", value, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateLessThan(String value) {
            addCriterion("EFFDATE <", value, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateLessThanOrEqualTo(String value) {
            addCriterion("EFFDATE <=", value, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateLike(String value) {
            addCriterion("EFFDATE like", value, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateNotLike(String value) {
            addCriterion("EFFDATE not like", value, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateIn(List<String> values) {
            addCriterion("EFFDATE in", values, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateNotIn(List<String> values) {
            addCriterion("EFFDATE not in", values, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateBetween(String value1, String value2) {
            addCriterion("EFFDATE between", value1, value2, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateNotBetween(String value1, String value2) {
            addCriterion("EFFDATE not between", value1, value2, "effdate");
            return (Criteria) this;
        }

        public Criteria andExpdateIsNull() {
            addCriterion("EXPDATE is null");
            return (Criteria) this;
        }

        public Criteria andExpdateIsNotNull() {
            addCriterion("EXPDATE is not null");
            return (Criteria) this;
        }

        public Criteria andExpdateEqualTo(String value) {
            addCriterion("EXPDATE =", value, "expdate");
            return (Criteria) this;
        }

        public Criteria andExpdateNotEqualTo(String value) {
            addCriterion("EXPDATE <>", value, "expdate");
            return (Criteria) this;
        }

        public Criteria andExpdateGreaterThan(String value) {
            addCriterion("EXPDATE >", value, "expdate");
            return (Criteria) this;
        }

        public Criteria andExpdateGreaterThanOrEqualTo(String value) {
            addCriterion("EXPDATE >=", value, "expdate");
            return (Criteria) this;
        }

        public Criteria andExpdateLessThan(String value) {
            addCriterion("EXPDATE <", value, "expdate");
            return (Criteria) this;
        }

        public Criteria andExpdateLessThanOrEqualTo(String value) {
            addCriterion("EXPDATE <=", value, "expdate");
            return (Criteria) this;
        }

        public Criteria andExpdateLike(String value) {
            addCriterion("EXPDATE like", value, "expdate");
            return (Criteria) this;
        }

        public Criteria andExpdateNotLike(String value) {
            addCriterion("EXPDATE not like", value, "expdate");
            return (Criteria) this;
        }

        public Criteria andExpdateIn(List<String> values) {
            addCriterion("EXPDATE in", values, "expdate");
            return (Criteria) this;
        }

        public Criteria andExpdateNotIn(List<String> values) {
            addCriterion("EXPDATE not in", values, "expdate");
            return (Criteria) this;
        }

        public Criteria andExpdateBetween(String value1, String value2) {
            addCriterion("EXPDATE between", value1, value2, "expdate");
            return (Criteria) this;
        }

        public Criteria andExpdateNotBetween(String value1, String value2) {
            addCriterion("EXPDATE not between", value1, value2, "expdate");
            return (Criteria) this;
        }

        public Criteria andChannelplayeridIsNull() {
            addCriterion("CHANNELPLAYERID is null");
            return (Criteria) this;
        }

        public Criteria andChannelplayeridIsNotNull() {
            addCriterion("CHANNELPLAYERID is not null");
            return (Criteria) this;
        }

        public Criteria andChannelplayeridEqualTo(String value) {
            addCriterion("CHANNELPLAYERID =", value, "channelplayerid");
            return (Criteria) this;
        }

        public Criteria andChannelplayeridNotEqualTo(String value) {
            addCriterion("CHANNELPLAYERID <>", value, "channelplayerid");
            return (Criteria) this;
        }

        public Criteria andChannelplayeridGreaterThan(String value) {
            addCriterion("CHANNELPLAYERID >", value, "channelplayerid");
            return (Criteria) this;
        }

        public Criteria andChannelplayeridGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNELPLAYERID >=", value, "channelplayerid");
            return (Criteria) this;
        }

        public Criteria andChannelplayeridLessThan(String value) {
            addCriterion("CHANNELPLAYERID <", value, "channelplayerid");
            return (Criteria) this;
        }

        public Criteria andChannelplayeridLessThanOrEqualTo(String value) {
            addCriterion("CHANNELPLAYERID <=", value, "channelplayerid");
            return (Criteria) this;
        }

        public Criteria andChannelplayeridLike(String value) {
            addCriterion("CHANNELPLAYERID like", value, "channelplayerid");
            return (Criteria) this;
        }

        public Criteria andChannelplayeridNotLike(String value) {
            addCriterion("CHANNELPLAYERID not like", value, "channelplayerid");
            return (Criteria) this;
        }

        public Criteria andChannelplayeridIn(List<String> values) {
            addCriterion("CHANNELPLAYERID in", values, "channelplayerid");
            return (Criteria) this;
        }

        public Criteria andChannelplayeridNotIn(List<String> values) {
            addCriterion("CHANNELPLAYERID not in", values, "channelplayerid");
            return (Criteria) this;
        }

        public Criteria andChannelplayeridBetween(String value1, String value2) {
            addCriterion("CHANNELPLAYERID between", value1, value2, "channelplayerid");
            return (Criteria) this;
        }

        public Criteria andChannelplayeridNotBetween(String value1, String value2) {
            addCriterion("CHANNELPLAYERID not between", value1, value2, "channelplayerid");
            return (Criteria) this;
        }

        public Criteria andDealFlagIsNull() {
            addCriterion("DEAL_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDealFlagIsNotNull() {
            addCriterion("DEAL_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDealFlagEqualTo(Integer value) {
            addCriterion("DEAL_FLAG =", value, "dealFlag");
            return (Criteria) this;
        }

        public Criteria andDealFlagNotEqualTo(Integer value) {
            addCriterion("DEAL_FLAG <>", value, "dealFlag");
            return (Criteria) this;
        }

        public Criteria andDealFlagGreaterThan(Integer value) {
            addCriterion("DEAL_FLAG >", value, "dealFlag");
            return (Criteria) this;
        }

        public Criteria andDealFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("DEAL_FLAG >=", value, "dealFlag");
            return (Criteria) this;
        }

        public Criteria andDealFlagLessThan(Integer value) {
            addCriterion("DEAL_FLAG <", value, "dealFlag");
            return (Criteria) this;
        }

        public Criteria andDealFlagLessThanOrEqualTo(Integer value) {
            addCriterion("DEAL_FLAG <=", value, "dealFlag");
            return (Criteria) this;
        }

        public Criteria andDealFlagIn(List<Integer> values) {
            addCriterion("DEAL_FLAG in", values, "dealFlag");
            return (Criteria) this;
        }

        public Criteria andDealFlagNotIn(List<Integer> values) {
            addCriterion("DEAL_FLAG not in", values, "dealFlag");
            return (Criteria) this;
        }

        public Criteria andDealFlagBetween(Integer value1, Integer value2) {
            addCriterion("DEAL_FLAG between", value1, value2, "dealFlag");
            return (Criteria) this;
        }

        public Criteria andDealFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("DEAL_FLAG not between", value1, value2, "dealFlag");
            return (Criteria) this;
        }

        public Criteria andOutParamIsNull() {
            addCriterion("OUT_PARAM is null");
            return (Criteria) this;
        }

        public Criteria andOutParamIsNotNull() {
            addCriterion("OUT_PARAM is not null");
            return (Criteria) this;
        }

        public Criteria andOutParamEqualTo(String value) {
            addCriterion("OUT_PARAM =", value, "outParam");
            return (Criteria) this;
        }

        public Criteria andOutParamNotEqualTo(String value) {
            addCriterion("OUT_PARAM <>", value, "outParam");
            return (Criteria) this;
        }

        public Criteria andOutParamGreaterThan(String value) {
            addCriterion("OUT_PARAM >", value, "outParam");
            return (Criteria) this;
        }

        public Criteria andOutParamGreaterThanOrEqualTo(String value) {
            addCriterion("OUT_PARAM >=", value, "outParam");
            return (Criteria) this;
        }

        public Criteria andOutParamLessThan(String value) {
            addCriterion("OUT_PARAM <", value, "outParam");
            return (Criteria) this;
        }

        public Criteria andOutParamLessThanOrEqualTo(String value) {
            addCriterion("OUT_PARAM <=", value, "outParam");
            return (Criteria) this;
        }

        public Criteria andOutParamLike(String value) {
            addCriterion("OUT_PARAM like", value, "outParam");
            return (Criteria) this;
        }

        public Criteria andOutParamNotLike(String value) {
            addCriterion("OUT_PARAM not like", value, "outParam");
            return (Criteria) this;
        }

        public Criteria andOutParamIn(List<String> values) {
            addCriterion("OUT_PARAM in", values, "outParam");
            return (Criteria) this;
        }

        public Criteria andOutParamNotIn(List<String> values) {
            addCriterion("OUT_PARAM not in", values, "outParam");
            return (Criteria) this;
        }

        public Criteria andOutParamBetween(String value1, String value2) {
            addCriterion("OUT_PARAM between", value1, value2, "outParam");
            return (Criteria) this;
        }

        public Criteria andOutParamNotBetween(String value1, String value2) {
            addCriterion("OUT_PARAM not between", value1, value2, "outParam");
            return (Criteria) this;
        }

        public Criteria andCreateDataIsNull() {
            addCriterion("CREATE_DATA is null");
            return (Criteria) this;
        }

        public Criteria andCreateDataIsNotNull() {
            addCriterion("CREATE_DATA is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDataEqualTo(Date value) {
            addCriterion("CREATE_DATA =", value, "createData");
            return (Criteria) this;
        }

        public Criteria andCreateDataNotEqualTo(Date value) {
            addCriterion("CREATE_DATA <>", value, "createData");
            return (Criteria) this;
        }

        public Criteria andCreateDataGreaterThan(Date value) {
            addCriterion("CREATE_DATA >", value, "createData");
            return (Criteria) this;
        }

        public Criteria andCreateDataGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATA >=", value, "createData");
            return (Criteria) this;
        }

        public Criteria andCreateDataLessThan(Date value) {
            addCriterion("CREATE_DATA <", value, "createData");
            return (Criteria) this;
        }

        public Criteria andCreateDataLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATA <=", value, "createData");
            return (Criteria) this;
        }

        public Criteria andCreateDataIn(List<Date> values) {
            addCriterion("CREATE_DATA in", values, "createData");
            return (Criteria) this;
        }

        public Criteria andCreateDataNotIn(List<Date> values) {
            addCriterion("CREATE_DATA not in", values, "createData");
            return (Criteria) this;
        }

        public Criteria andCreateDataBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATA between", value1, value2, "createData");
            return (Criteria) this;
        }

        public Criteria andCreateDataNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATA not between", value1, value2, "createData");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SUBSINST_SYN_TEMP
     *
     * @mbg.generated do_not_delete_during_merge Thu May 26 09:46:38 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SUBSINST_SYN_TEMP
     *
     * @mbg.generated Thu May 26 09:46:38 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}